// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5RHjFX0yFaPmWT9rwJ15kP059HCWmuNQ',
    appId: '1:698738692116:web:70dc87df40534ed8fed701',
    messagingSenderId: '698738692116',
    projectId: 'satinstone-27cc0',
    authDomain: 'satinstone-27cc0.firebaseapp.com',
    storageBucket: 'satinstone-27cc0.firebasestorage.app',
    measurementId: 'G-4XCHKE1B87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0oQpbxXwaqmFjWe0VLwH8OTMhssdbrYg',
    appId: '1:698738692116:android:4b913741051c4a75fed701',
    messagingSenderId: '698738692116',
    projectId: 'satinstone-27cc0',
    storageBucket: 'satinstone-27cc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbwwQaS-MSWGIrAzALSF4TaHcr65ZxF54',
    appId: '1:698738692116:ios:d9615e99f21c9668fed701',
    messagingSenderId: '698738692116',
    projectId: 'satinstone-27cc0',
    storageBucket: 'satinstone-27cc0.firebasestorage.app',
    iosBundleId: 'com.example.fashionApp',
  );
}
